//LOS OPERADORES ARITMETICOS.

4 + 4 //SUMA
5 - 4 //RESTA
2 + 4 //MULTIPLICACION
5 / 7 //DIVISION
5 == 5 //ES IGUAL QUE
5 == 5 //ESTRICTAMENTE IGUAL QUE, TOMA EN CUENTA EL TIPO DE DATO TAMBIEN.
5 > 6 //ES MAYOR QUE
5 < 6 //ES MENOR QUE
!Boolean(0) // ! = SIGNIFICA NEGACION.
5 ** 2 //OPERADOR DE POTENCIA.
4 % 5 //OPERADOR DE MODULO.

//OPERADORES LOGICOS. (LOGIC OPERATORS)
a = 10
b = 20
a && b // "Y" MULTIPLICA, ES DECIR, LOS DOS SE TIENEN QUE CUMPLIR PARA QUE SEA TRUE.
a || b // "OR" SUMA, ES DECIR QUE ALGUNO DE LOS DOS SE CUMPLE PARA QUE SEA TRUE.

//COSAS CURIOSAS LEARNED TODAY:
Nan //NOT A NUMBER ES DECIR QUE ES FALSY.

